apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: ewat-jitter
  namespace: ewat
  labels:
    ewat.scenario: jitter
    ewat.category: gray
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - ewat
    labelSelectors:
      app.kubernetes.io/component: currency
  delay:
    latency: "50ms"
    jitter: "200ms"
    correlation: "75"
  direction: both
  duration: "2m"
