apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: ewat-io-error
  namespace: ewat
  labels:
    ewat.scenario: io_error
    ewat.category: contention
spec:
  action: fault
  mode: all
  selector:
    namespaces:
      - ewat
    labelSelectors:
      app.kubernetes.io/component: accounting
  volumePath: /data
  path: "/data/**/*"
  errno: 5  # EIO
  percent: 50
  duration: "2m"
