apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: ewat-network-loss
  namespace: ewat
  labels:
    ewat.scenario: network_loss
    ewat.category: hard
spec:
  action: loss
  mode: all
  selector:
    namespaces:
      - ewat
    labelSelectors:
      app.kubernetes.io/component: frontend
  direction: to
  target:
    mode: all
    selector:
      namespaces:
        - ewat
      labelSelectors:
        app.kubernetes.io/component: recommendation
  loss:
    loss: "100"
  duration: "1m"
